language: node_js
node_js:
- 8
script:
- npm run build
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAIEGZXIUUOLOHQIQA
  secret_access_key: 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
  bucket: ec-illinois.org
  local-dir: build
  acl: public_read_write
  on:
    repo: ec-illinois/ec-website
  region: us-east-2
  skip_cleanup: true
